### PR TITLE
Feature: upgrade yara to 4.1.3

### PR DESCRIPTION
**Pull request by ikrivosheev**
Upgrade yara to 4.1.3

### CODE REVIEW

**Review by Hugal31 — COMMENTED** [review]
Can you be sure the two bundled bindings file are ABI-compatible?

**Comment by ikrivosheev** [comment]
> Can you be sure the two bundled bindings file are ABI-compatible?

Yes, I run `bindgen` for new yara version

**Comment by Hugal31** [comment]
Whoops, did I broke something?

**Comment by ikrivosheev** [comment]
> Whoops, did I broke something?

No, test: `rules_scan_proc` is unstable...

**Pull request merged**
