### PR TITLE
deps: update to bindgen 0.66

### PR DESCRIPTION
**Pull request by poliorcetics**

### CODE REVIEW

**Comment by ikrivosheev** [comment]
@poliorcetics hello! Do we need to regenerate generated files?

**Comment by poliorcetics** [comment]
maybe, I have no idea, I'll try it

**Comment by poliorcetics** [comment]
no I don't think so

the macos build also fail on `master` but the lint failures are new, maybe Rust 1.71 (since `stable` is used)

**Comment by Hugal31** [comment]
I've fixed the pipeline. Can you merge/rebase master into your branch?

**Pull request merged**
