### PR TITLE
fix: bundled_3.X on windows

### PR DESCRIPTION
**Pull request by Orycterope**
A proposal to address #19, tell me what you think of it.

I've renamed bindings/yara-3.X.rs to bindings/yara-3.X-unix.rs, and generated bindings/yara-3.X-windows.rs with bindgen. Looking at the diff, you'll see that besides private internal structure layout and types, in the actually exposed API only the functions that take in a fd differ. 

I've updated the yara-sys/build.rs to use the right file at compile time.

And finally I've added two scenarios in .tarvis-ci.yml:

```
TARGET=x86_64-pc-windows-msvc   YARA_FEATURES=vendored,bundled-3_11
TARGET=x86_64-pc-windows-msvc   YARA_FEATURES=vendored,bundled-3_8
``` 

The second one is technically invalid, since it uses 3.8 bindings on a 3.11 lib built by cc (vendored), but because of backcompability it should work.

### CODE REVIEW

**Comment by Hugal31** [comment]
I like the approach (with the -unix and -windows bundled files), but the CI is failing.
Also, I might wait for the 4.x support (#13) to merge this.

**Comment by Hugal31** [comment]
One thing you might want to know I just remembered - the current .travis-ci.yaml lacks a `--no-default-features` flags, so bindgen is always used IIRC. This might cause the problems you have with the CI.

**Comment by Orycterope** [comment]
Yes ! I've already fixed that, but now I'm witnessing a SIGSEV on linux when running the tests when I compile with `--features vendored,bundled-3_8`, (i.e. 3.11 lib built with cc with 3.8 bundled bindings).

The `scanner::test::external_vars_on_file` crashes in the callback when trying to convert a null YR_STRING, failing to recognize it's the end of the array. I'm still investigating it.

**Comment by Orycterope** [comment]
Ahahah ok I've found out why: [some fields](https://github.com/VirusTotal/yara/commit/37aae685c20a621f61ff8f7187b6c948a87004eb#diff-5217a37ae8127dc35224c16750f610f0730412057a74d7a6f86e24fc3df2ffc4R279) were added in YR_STRING between v3.8 and v3.11, which means its size changed, and iterating an array of struct with the wrong struct size won't work. 

This means that my assumption that using a libyara 3.11 with 3.8 bindings will work **is wrong and will lead to segfault**. I think this should at least be documented in the readme

I'm removing these configurations in travis

**Comment by Hugal31** [comment]
LGTM! I'll merge and replicate the same in the Yara v4.0 PR. 

I didn't knew you could give multiple env var per line in the travis-ci.yaml:
```yaml
env:
  jobs:
    - YARA_VERSION=3.8.1  YARA_FEATURES=bindgen
    - YARA_VERSION=3.8.1  YARA_FEATURES=bundled-3_8
 ```

I was looking for a way to do this for #13 and didn't find it in the documentation.
Thanks!

**Pull request merged**
