### PR TITLE
Add MacOS build

### PR DESCRIPTION
**Pull request by ikrivosheev**
Fix: https://github.com/Hugal31/yara-rust/issues/40

I only added build without tests, since I am having problems with test on MacOS: https://github.com/ikrivosheev/yara-rust/runs/3270599324?check_suite_focus=true#step:4:204

### CODE REVIEW

**Comment by ikrivosheev** [comment]
@Hugal31 can you review this PR? Thank you)

**Comment by ikrivosheev** [comment]
@hexgnu ping?)

**Comment by hexgnu** [comment]
I don't know if I'm the right person to review this since I don't own a mac.

From the glance of it it looks good to me though :).

**Comment by ikrivosheev** [comment]
@hexgnu, @hexgnu, it might be worth adding flags for static linking with: OpenSSL, libmagic, jansson?

**Comment by hexgnu** [comment]
Yea I mean that makes sense

**Comment by Hugal31** [comment]
LGTM, I'm merging. Thank you!

Sorry for the delay.

**Pull request merged**
