### PR TITLE
feat: upgrade yara to 4.2.1

### PR DESCRIPTION
**Pull request by ikrivosheev**
New version for yara is released: https://github.com/VirusTotal/yara/releases/tag/v4.2.0.

### CODE REVIEW

**Comment by vthib** [comment]
Any news on this update? I've tested it locally on a linux setup (with vendored and vendored,bundled-4_2_0) and it works fine, i'm not sure what the check failures are

**Comment by ikrivosheev** [comment]
> Any news on this update? I've tested it locally on a linux setup (with vendored and vendored,bundled-4_2_0) and it works fine, i'm not sure what the check failures are

I so sorry for the delay, I have some problems with my laptop. I will finish in 2-3 days

**Comment by ikrivosheev** [comment]
@vthib I think I found bug in yara c library. Bug is infinity loop when scan process by pid. 

I will report today.

**Comment by ikrivosheev** [comment]
@vthib @Hugal31 done for Linux and MacOs. I upgrade yara to **4.2.1**. Can someone generate `bindgen` for Windows?

**Comment by Hugal31** [comment]
Isn't there a way to run bindgen on Windows via Github actions and retrieved the generated files? I think this has been done when the project used Travis.

**Comment by ikrivosheev** [comment]
> Isn't there a way to run bindgen on Windows via Github actions and retrieved the generated files? I think this has been done when the project used Travis.

Good idea. I think about this, I will try to make it.

**Comment by vthib** [comment]
I have generated the bindings for the `x86_64-pc-windows-msvc` target, here it is: https://pastebin.com/fiFgjpxA

**Comment by ikrivosheev** [comment]
@vthib thank you!

**Comment by ikrivosheev** [comment]
@Hugal31 what do you think if I make this:

> Isn't there a way to run bindgen on Windows via Github actions and retrieved the generated files? I think this has been done when the project used Travis.

In other PR?

**Comment by ikrivosheev** [comment]
@vthib thank you! `yara-sys` now build for Windows

**Pull request merged**
