### PR TITLE
Add compatibility to yara 4.0

### LINKED ISSUE #11: Yara v4.0.2 support
Hi,

May I ask you to support for Yara > 4.0.0 ?
Next Debian stable release (bullseye) will come directly with yara & libyara = v4.0.2.
Many thanks for your help !
Cheers

### PR DESCRIPTION
**Pull request by Hugal31**
Attempt to make yara and yara-sys compatible with libyara 4.0.2

It turns out that keeping the 3.X compatibility will be harder than I though.

Closes #11

### CODE REVIEW

**Comment by r3dlight** [comment]
Hi Hugal31,

So this release will definitely break any libyara 3.x compatibility ?

**Comment by Hugal31** [comment]
The idea is not to break any compatibility, if I can manage to. I can't say for sure now.

**Comment by Hugal31** [comment]
Well, now I can say for sure I will not achieve compatibility with both version: there are two much breaking change for me to abstract those without creating a mess. I'll drop compatibility to Yara v3 when releasing a Yara v4 compatible version.

**Comment by Orycterope** [comment]
Hey ! 

I love what you did with this crate, but I too need support for v4. Do you know when this PR will be completed ? 

Can I contribute in any way ?

**Comment by Hugal31** [comment]
Since I forfeit keeping 3.X compatibility, I planned on working on this this week-end. I'm not sure how big the work will be.

**Comment by Hugal31** [comment]
Just so I know, why do you want Yara v4.X? For new rule syntax, for example, or for new API capabilities? Just so I know if I have to add features.

**Comment by Hugal31** [comment]
This is ready for merge, I am just waiting a bit for yara-src to answer so I can keep the `vendored` feature with Yara v4.0

**Comment by r3dlight** [comment]
Not sure if you've seen this but lazy_static depends on spin (<0.5.2) which seems to be vulnerable to memory corruption, see https://deps.rs/crate/lazy_static/1.3.0
Hoping lazy_static v0.4.1 is coming soon (https://github.com/rust-lang-nursery/lazy-static.rs/pull/186), it might be interesting to wait for this new version.

**Comment by mat-gas** [comment]
Any news on this PR? yara-src seems to be quite down ATM (no commit for the last 4 months, 1 waiting PR since a month ago)

**Comment by Hugal31** [comment]
I am waiting for https://github.com/rust-lang-nursery/lazy-static.rs/pull/186.

For yara-src, I am not sure what I should do. I cloud drop support for the `vendored` feature, I could try to claim the crate on crates.io or publish an alternative crate (I am not fond of that).

What do you think ?

**Comment by Orycterope** [comment]
I'm a big user of the `vendored` feature, it works well, even in my cross-compilation use case, and I don't want to have to compile the lib myself for all my targets and have to store them somewhere. 

I personally think yara-src-rs shouldn't be a separate crate, and it's so small it could easily live in the `build.rs` of this crate. I think this is the best solution for this situation: you as a maintainer get more control over what sources and what version you compile, you don't have to claim ownership of yara-src-rs, and you no longer depend on it. 

I'm going to write a PR that does the copy-pasta today.

**Comment by Hugal31** [comment]
Sounds good to me. Thanks!

**Pull request merged**
