### PR TITLE
fix: unit test scanner_scan_proc utf-16 encoding

### LINKED ISSUE #25: scanner::test::scanner_scan_proc fails randomly on Windows
This can be see in some [Travis jobs](https://travis-ci.org/github/Hugal31/yara-rust/jobs/768577253): sometimes, the test `scanner::test::scanner_scan_proc` fails on Windows.

### PR DESCRIPTION
**Pull request by Orycterope**
An attempt to fix #25 by extending the timeout. Let's see if it works.

### CODE REVIEW

**Comment by Orycterope** [comment]
Aaaand the test still fails, so seems it's not a timeout problem ... 

I really don't get it, and I can't manage to reproduce it on my windows VM. Do you encounter it on any of your machines ?

**Comment by Hugal31** [comment]
I don't usually code on Windows, so I've never tried to reproduced it.

**Comment by Orycterope** [comment]
Maybe this is an encoding problem with the needle string ? (Yes I'm desperate at this point)

**Comment by Orycterope** [comment]
So this **was** an encoding problem ! On windows, the string is present in cmd's memory, but only in utf-16 format. I've updated the test case to look only for `wide` strings on windows. 

The test worked in my windows VM because somehow the string must have been also present in utf-8 form.

**Comment by Hugal31** [comment]
Good catch! Thank you very much!

**Pull request merged**
